[package]
name = "yml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cargo add serde
serde = "1.0.169"
# cargo add serde_yaml
serde_yaml = "0.9.22"
